package com.example.test_asesoftware.utils

const val IMAGE_URL = "https://homecenterco.scene7.com/is/image/SodimacCO/257403_13?producto495$&iv=hfRH2&wid=80&hei=80"
const val LAVADORA = "Lavadora"
const val COCINA = "Cocina"
const val NEVERA = "Nevera"
const val TV = "Televisor"
const val RADIO = "Radio"
const val LAVADORA_PRICE  = "1000"
const val NEVRA_PRICE  = "2050"
const val TV_PRICE = "3561"
const val RADIO_PRICE = "5226"
const val COCINA_PRICE = "2003"
const val LAVADORA_DES = "Lavadora dos tambores"
const val NEVRA_DES  = "Nevera de dos puertas"
const val TV_DES = "Smar Tv 65 pulgadas"
const val RADIO_DES= "Radio de 2000 Watts"
const val COCINA_DES = "Cocina industrial"
